# Generated by Django 6.0.2 on 2026-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('anio_publicacion', models.IntegerField()),
                ('editorial', models.CharField(max_length=100)),
            ],
        ),
    ]
