# Generated by Django 6.0.2 on 2026-02-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_libro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fuente',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
